// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/base.h"

WINRT_WARNING_PUSH

static_assert(winrt::check_version(CPPWINRT_VERSION, "1.0.180227.3"), "Mismatched component and base headers.");
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/winrtcppcoawaitBlankApp1.2.h"

namespace winrt::impl {

template <typename D> int32_t consume_winrtcppcoawaitBlankApp1_IMainPage<D>::MyProperty() const
{
    int32_t result{};
    check_hresult(WINRT_SHIM(winrtcppcoawaitBlankApp1::IMainPage)->get_MyProperty(&result));
    return result;
}

template <typename D> void consume_winrtcppcoawaitBlankApp1_IMainPage<D>::MyProperty(int32_t value) const
{
    check_hresult(WINRT_SHIM(winrtcppcoawaitBlankApp1::IMainPage)->put_MyProperty(value));
}

template <typename D>
struct produce<D, winrtcppcoawaitBlankApp1::IMainPage> : produce_base<D, winrtcppcoawaitBlankApp1::IMainPage>
{
    HRESULT __stdcall get_MyProperty(int32_t* result) noexcept final
    {
        try
        {
            typename D::abi_guard guard(this->shim());
            *result = detach_from<int32_t>(this->shim().MyProperty());
            return S_OK;
        }
        catch (...)
        {
            return to_hresult();
        }
    }

    HRESULT __stdcall put_MyProperty(int32_t value) noexcept final
    {
        try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return S_OK;
        }
        catch (...)
        {
            return to_hresult();
        }
    }
};

}

WINRT_EXPORT namespace winrt::winrtcppcoawaitBlankApp1 {

inline MainPage::MainPage() :
    MainPage(get_activation_factory<MainPage>().ActivateInstance<MainPage>())
{}

}

WINRT_EXPORT namespace std {

template<> struct hash<winrt::winrtcppcoawaitBlankApp1::IMainPage> : winrt::impl::hash_base<winrt::winrtcppcoawaitBlankApp1::IMainPage> {};
template<> struct hash<winrt::winrtcppcoawaitBlankApp1::MainPage> : winrt::impl::hash_base<winrt::winrtcppcoawaitBlankApp1::MainPage> {};

}

WINRT_WARNING_POP
